version: '2'
services:
  mrp:
    image: "acdh/mrp"
    labels:
      - traefik.backend=mrp
      - traefik.frontend.rule=Host:mrp.sisyphos.arz.oeaw.ac.at
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - web
    build:
      context: .
      dockerfile: Dockerfile
networks:
  web:
    external:
      name: web
